name: GuessTheAnimal
version: 0.2.0.0
github: "michaelecrippa/GuessTheAnimal"
license: MIT
author: "Michael Crippa"
maintainer: "michaelecrippa@gmail.com"
copyright: "2021 Michael Crippa"

extra-source-files: []

description: Please see the README on GitHub at <https://github.com/michaelecrippa/GuessTheAnimal>

dependencies:
- base >= 4.7 && < 5
- HUnit

library:
  source-dirs: src

executables:
  GuessTheAnimal-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - GuessTheAnimal

tests:
  GuessTheAnimal-test:
    main: Spec.hs
    source-dirs: tests
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - GuessTheAnimal
